### ISSUE TITLE
Email translation problems when the order is created by the OEN-handler

### ISSUE THREAD

**Issue by bve-9384** [evalentgroup/Magento-2-Ecster-Pay#11] opened 2020-08-22 15:23 UTC
The "order summary" part of the order confirmation email is not in the local language if the order is created by the OEN-handler, for instance:
![image](https://user-images.githubusercontent.com/25124716/90959505-dbfbd680-e49b-11ea-990a-b85a9749ee2d.png)

The order confirmation email does not have this problem when created by the frontend or admin

**Comment by TobiasLufinity** [comment] 2020-08-24 09:30
Was not able to reproduce this locally but I've added the code that fixed it for you but in another place. 
We only need to load the translation when creating an order and not on every OEN call. 
This will be released later today

**Comment by TobiasLufinity** [comment] 2020-08-24 12:50
Released in version 1.0.4

**Closed by TobiasLufinity** 2020-08-24 12:50 UTC
