### ISSUE TITLE
Possible to checkout without selecting a shipping option

### ISSUE THREAD

**Issue by bve-9384** [evalentgroup/Magento-2-Ecster-Pay#9] opened 2020-06-27 08:56 UTC
It is possible to checkout without selecting a shipping option. The Ecster payment is successful but the Magento Order is not created, error: "The shipping method is missing. Select the shipping method and try again."

We have the following setup:
- Sweden: Free Shipping only
- Other countries: Table Rates Shipping only

Flow:
1) Add an item to the shopping basket
2) Enter Checkout 
         ==> the default country "Sweden" is selected
         ==> free shipping is selected
3) Change the country in Checkout
         ==> the new country is selected
         ==> Table Rates shipping is shown as the only shipping option but is not selected
4) One can continue checkout without selecting the shipping option
5) The Ecster payment is completed but the Magento order is not. Error "The shipping method is missing. Select the shipping method and try again."

Expected behaviour:
- Automatic selection of shipping option if only one shipping option is available after switching countries.
- Checkout not possible as long as a shipping option is not selected

**Comment by TobiasCodeNull** [comment] 2020-07-15 10:44
Thanks for finding this issue and for a well formed flow chart to reproduce the bug.

The issue is now fixed and will be released in the 1.0.2 release.
Feel free to test using "dev-develop as 1.0.1" in you composer.json and get back to us if the issue persist.

**Closed** 2020-07-15 11:47 UTC
Labels: bug

**Comment by bve-9384** [comment] 2020-07-16 12:46
@TobiasCodeNull This issue seems to be solved now in version 1.0.2 :-) but when testing I noted that the customer can change the country in the delivery address section (Leveransadress) as well, without having to select a new shipping option. Shouldn't this second country field be read only? It also makes it possible to select Swish and Invoice payment options in all countries.
